# Generated by Django 5.2 on 2025-10-17 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class_cancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='休講情報')),
            ],
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateTimeField(verbose_name='締め切り')),
                ('content', models.TextField(blank=True, verbose_name='内容')),
            ],
        ),
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, verbose_name='内容')),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100, verbose_name='授業名')),
                ('professor_name', models.CharField(max_length=100, verbose_name='教授名')),
                ('classroom_name', models.CharField(max_length=100, verbose_name='教室名')),
                ('day_of_the_week', models.IntegerField(choices=[(0, '日曜日'), (1, '月曜日'), (2, '火曜日'), (3, '水曜日'), (4, '木曜日'), (5, '金曜日'), (6, '土曜日')], verbose_name='曜日')),
                ('period', models.IntegerField(choices=[(1, '1限目'), (2, '2限目'), (3, '3限目'), (4, '4限目'), (5, '5限目'), (6, '6限目'), (7, '7限目'), (8, '8限目')], verbose_name='時限')),
                ('attendance_count', models.IntegerField(default=0, verbose_name='出席回数')),
                ('absence_count', models.IntegerField(default=0, verbose_name='欠席回数')),
                ('total_late_and_early_leave_count', models.IntegerField(default=0, verbose_name='遅刻・早退回数')),
                ('belongings', models.TextField(blank=True, verbose_name='持ち物')),
                ('examination', models.TextField(blank=True, verbose_name='試験日程')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('class_cancellations', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.class_cancellation', verbose_name='休講情報')),
                ('homeworks', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.homework', verbose_name='宿題')),
                ('memos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.memo', verbose_name='メモ')),
            ],
        ),
    ]
