# Generated by Django 5.2.7 on 2025-10-17 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='class_cancellations',
        ),
        migrations.AlterField(
            model_name='class',
            name='day_of_the_week',
            field=models.IntegerField(choices=[(0, '日曜日'), (1, '月曜日'), (2, '火曜日'), (3, '水曜日'), (4, '木曜日'), (5, '金曜日'), (6, '土曜日')], verbose_name='曜日'),
        ),
        migrations.RemoveField(
            model_name='class',
            name='homeworks',
        ),
        migrations.RemoveField(
            model_name='class',
            name='memos',
        ),
        migrations.AddField(
            model_name='class',
            name='class_cancellations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.class_cancellation', verbose_name='休講情報'),
        ),
        migrations.AddField(
            model_name='class',
            name='homeworks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.homework', verbose_name='宿題'),
        ),
        migrations.AddField(
            model_name='class',
            name='memos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.memo', verbose_name='メモ'),
        ),
    ]
