# Generated by Django 5.2.7 on 2025-10-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_class_day_of_the_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='belongings',
            field=models.TextField(blank=True, null=True, verbose_name='持ち物'),
        ),
        migrations.AlterField(
            model_name='class',
            name='classroom_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='教室名'),
        ),
        migrations.AlterField(
            model_name='class',
            name='examination',
            field=models.TextField(blank=True, null=True, verbose_name='試験日程'),
        ),
        migrations.AlterField(
            model_name='class',
            name='professor_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='教授名'),
        ),
    ]
