# Generated by Django 5.2.7 on 2025-10-29 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_class_belongings_alter_class_classroom_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='examination',
            field=models.DateField(blank=True, null=True, verbose_name='試験日程'),
        ),
        migrations.AlterField(
            model_name='class_cancellation',
            name='date',
            field=models.DateField(verbose_name='休講情報'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='deadline',
            field=models.DateField(verbose_name='締め切り'),
        ),
    ]
