# Generated by Django 5.2 on 2025-11-26 02:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_class_schedule_class_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='class_cancellation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='作成日時'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homework',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='作成日時'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-11-26 00:00:00', verbose_name='作成日時'),
            preserve_default=False,
        ),
    ]
