# Generated by Django 5.2.7 on 2025-12-02 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_class_cancellation_created_at_homework_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homework',
            old_name='classModel',
            new_name='class_model',
        ),
    ]
