# Generated by Django 5.2.7 on 2025-12-23 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_classmodel_homework_class_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='is_finished',
            field=models.BooleanField(default=False, verbose_name='完了済み'),
        ),
    ]
