# Generated by Django 5.2.7 on 2026-01-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_class_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='color',
            field=models.CharField(choices=[('#f5f5f5', 'グレー'), ('#ffebee', 'レッド'), ('#fff3e0', 'オレンジ'), ('#fffde7', 'イエロー'), ('#f1f8e9', 'グリーン'), ('#e1f5fe', 'ブルー'), ('#f3e5f5', 'パープル'), ('#e0f2f1', 'ミント')], default='#f5f5f5', max_length=7, verbose_name='色'),
        ),
    ]
